//
// Generated file, do not edit! Created by nedtool 5.6 from message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>message.msg:2</tt> by nedtool.
 * <pre>
 * message sendMsg
 * {
 *     int source;
 *     int destination;
 *     int payload;
 * }
 * </pre>
 */
class sendMsg : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int payload;

  private:
    void copy(const sendMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const sendMsg&);

  public:
    sendMsg(const char *name=nullptr, short kind=0);
    sendMsg(const sendMsg& other);
    virtual ~sendMsg();
    sendMsg& operator=(const sendMsg& other);
    virtual sendMsg *dup() const override {return new sendMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getPayload() const;
    virtual void setPayload(int payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const sendMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, sendMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MESSAGE_M_H

